# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ai-fcp-techspike-python:
    build:
      target: development
    image: ai-fcp-techspike-python-development
    container_name: ai-fcp-techspike-python-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

networks:
  ai-fcp-techspike-python:
    name: ai-fcp-techspike-python
    driver: bridge
