{{- include "ffc-helm-library.container-config-map" (list . "ai-fcp-techspike-python.config-map") -}}
{{- define "ai-fcp-techspike-python.config-map" -}}
data:
  NODE_ENV: {{ .Values.environment | quote }}
  PORT: {{ .Values.container.port | quote }}
  APPINSIGHTS_CLOUDROLE: {{ .Chart.Name | quote }}
{{- end -}}
