{{- include "ffc-helm-library.container-secret" (list . "ai-fcp-techspike-python.container-secret") -}}
{{- define "ai-fcp-techspike-python.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ .Values.appInsights.connectionString | quote }}
  {{- end }}
{{- end -}}
