# Required values to support CI pipeline
environment: production
environmentCode:
name: ai-fcp-techspike-python
namespace: ffc-rps-experiment
workstream: ffc-rps-experiment
image: ai-fcp-techspike-python

appInsights:
  connectionString:

labels: {}

containerConfigMap: {}

containerSecret: {}

deployment: {}

port: &port 3000

container:
  resourceTier: M
  port: *port

ingress:
  class: nginx
  endpoint: ai-fcp-techspike-python
  server: ffc.snd.azure.defra.cloud

livenessProbe:
  path: /healthz
  port: *port
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: *port
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

# Enable if Managed Identity is required, ensure the clientID and resourceID are set in Platform Configuration
azureIdentity:
  enabled: false
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
